---
title: "Untitled"
author: "Tristan Mahr"
date: "2025-04-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
wisclabmisc::data_acq_consonants |> 
  print(n = Inf)
```


Which speech sounds are more or less difficult for children to produce? Phonetic 
complexity scores (`sss` and `ttt`) assign the speech sounds different 
complexity levels based on biological principles outlined in Kent (1992), but 
the provenance of these scores is worth presenting.

Sander (1972) set out to construct a set of developmental norms for
typical consonant acquisition in English. His big idea was to include
the median age of acquisition as well as the 90th percentile age of
acquisition. The median can tell us something about the average
acquisition of the speech sounds, and the 90th percentile can set a
benchmark for delayed acquisition. There are some quirks of the
methodology. First, Sander (1972) was targeting "customary articulation"
which was defined using production accuracy average across word
positions. So, the age of 50% customary articulation for /t/ is the
earliest age when the average of word-initial accuracy, word-medial
accuracy and word-final accuracy is greater than 50%. Second, the norms
for this study created augmenting the norms from 3--8-year-olds
(Templin, 1957; *n* = 480) with some earlier data for 2-year-olds
(Wellman et al. 1931; *n* = 15). 

Sander presented these acquisition norms in the following figure:

```
figure
```

Kent (1992) aimed to explain the course of English sound development in
terms of biological and motoric principles. He examined the ages of 90%
acquisition from Sander (1972)---that is, the right edges of the bars in
the previous figures---and observed that /p m n w h/ are mastered at
age 3, /b d k g j f/ at age 4, /t ŋ r l/ at age 6 and /s z ʃ ʒ v θ ð tʃ
dʒ/ after age 7. He then described motoric demands in each of these sets
of sounds. I'll paraphrase:

  - Set 1 requires fast "ballistic" movements for stops /p m n/, slow
    "ramp" movements for /w h/, velopharyngeal control for oral-nasal
    contrast, laryngeal control for voicing contrast.
  - Set 2 adds more stops /b d k g/ and another ramp /j/ and a new place
    of articulation (velars), but also requires "fine force regulation
    for frication" for /f/.
  - Set 3 adds more stops /t ŋ/, but also requires tongue "bending" for
    /r/ and /l/.
  - Set 4 adds more lingual fricatives /s z ʃ ʒ θ ð/ which require
    tongue bending and fine force control along with /v tʃ dʒ/. Kent
    does not characterize the motor demands for the affricates /tʃ dʒ/.

Let's pause for a moment and observe that this breakdown is just an
attempt to describe the Sander (1972) norms, and it is somewhat
underdeveloped. For example, why is /t/ in Set 3 but /d/ in Set 2? It is
not answered here, but I think this late mastery is an artefact of
Sander's requirement of 90% accuracy averaging over the three
word-positions. The medial and final productions of /t/ might require
allophonic variation in /t/ (e.g., flapping or glottalization), so
mastery of /t/ would require different motor gestures and some
phonological knowledge on the part of the child. But in Kent's
description /t/ is a later-mastered ballistic movement.

Still, the main point of Kent's description, I think, is that lingual
(tongue) consonants are more difficult. Elsewhere in the chapter, Kent
(1992) describes how the tongue is a "muscular hydrostat" like an
elephant trunk, and bending a hydrostat requires coordination of
different muscle directions:

"*Gaining motor control over a hydrostat presents some special problems
to the young child learning speech. For one, bending the hydrostat is
unlike bending a jointed structure such as a finger. The tongue has no
joints per se; it flexes by appropriate contraction of its
three-dimensional network of intrinsic longitudinal, vertical, and
transverse fibers. Bending a hydrostat requires that muscle fibers be
shortened on one aspect simultaneously with a resistance to a change in
diameter (Smith and Kier 1989). If the diameter change is not resisted,
then the hydrostat will shorten on one side but will not bend. To use
the tongue in speech, the child must learn to control the tongue to meet
skeletal, movement, and shaping requirements, often simultaneously.
These special characteristics of the tongue may well play a role in
vowel and consonant mastery.*"

Kim and colleagues (2010) applied these developmental sets as articulatory complexity "levels" while examining consonant errors in dysarthric speech. They then asked questions such as whether more complex consonants had more consonant errors than less complex ones (*yes*) or whether lower intelligibility speakers made more complexity-reducing consonant substitutions than higher intelligibility speakers (*apparently so*).


Allison and Hustad (2014) used these complexity levels as a way to *score* the phonetic complexity of sentences. They assigned consonants 1--5 scores (the 1--4 complexity levels with 5 for consonants clusters), and summed up the scores to provide a complexity score for a sentence. 

Kent (1992) also described the yearly developmental progression of
vowels. I'll paraphrase again:

  - By age 1: Infants produce *vocants* (vowel precursors) which
    correspond to the low-front, central and low-back vowels /æ ɛ ʌ ə
    ɑ/. Thus, the tongue only moves in the anterior-posterior direction
    (i.e., there is limited up-down movement).
  - By age 2: Toddlers produce the "maximally dissimilar" corner vowels
    /i u ɑ/ and produce /o/ and the central vowels /ʌ ə/.
  - By age 3: Children incorporate two lower vowels /ɛ ɔ/ and the
    diphthongs /aɪ aʊ ɔɪ/ which require gliding movements.
  - By age 4: Children incorporate the remaining non-rhotic vowels /ʊ ɪ
    e æ/. The appearance of the front vowels suggests that tongue-jaw
    coordination is a relatively late motor achievement. (/i/ appears
    earlier because its extreme height is easy.)
  - Lastly: Children incorporate /ɚ ɝ/ last because these r-colored
    vowels require tongue bending.

Kuruvilla-Dugdale and colleagues (2018) used this description to incorporate vowels into the phonetic complexity scale. Because vowels (or rather vocants) precede consonants, they mark the bottom of the complexity scale:



